name: .NET

env:
  GITHUB_USER: Nihlus
  GITHUB_FEED: https://nuget.pkg.github.com/Nihlus
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            6.0.x
            7.0.x
            8.0.x

      - name: Build
        run: |
          dotnet restore
          dotnet build -c Release --no-restore

      - name: Test
        run: dotnet test -c Release --no-restore --no-build --verbosity minimal

      - name: Inspect
        uses: JetBrains/ReSharper-InspectCode@v0.3
        with:
          tool-version: 2023.3.4
          solution: StrictEmit.sln
          build: false
          no-build: true
          telemetry-optout: true

      - name: Package
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: dotnet pack -c Release --no-restore --no-build --version-suffix "github$GITHUB_RUN_ID"
      - uses: actions/upload-artifact@v4
        with:
          name: nupkg
          path: nuget/*
    permissions:
      security-events: write
  prerelease:
    needs: build
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - name: Download package artifacts
        uses: actions/download-artifact@v4
        with:
          name: nupkg
          path: nuget

      # To ensure that the current version being pushed does not get pruned we prune first.
      - name: Prune packages older than 4 versions (new version is the 5th)
        uses: smartsquaregmbh/delete-old-packages@v0.8.0
        with:
          user: Nihlus
          type: nuget
          keep: 4
          names: |
            StrictEmit

      - name: Push to GitHub Feed
        run: |
          for f in ./nuget/*; do
            curl -vX PUT -u "$GITHUB_USER:$GITHUB_TOKEN" -F package=@$f $GITHUB_FEED
          done
